import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@newformdemo/client/providers/trcpprovider";
import Dashboard from "./components/dashboard";
import { AppFlowContextProvider } from "@/providers/appflow";

const fontSans = Roboto({
  variable: "--font-newform-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.className} font-newform! antialiased`}>
        <TRPCProvider>
          <AppFlowContextProvider>
            <Dashboard>{children}</Dashboard>
          </AppFlowContextProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
