import type { Metadata } from "next";
import { Epilogue, Roboto } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@newformdemo/client/providers/trcpprovider";
import { AppFlowContextProvider } from "@/providers/appflow";
import { WillBotTourProvider } from "@/providers/willbottour";

const fontSans = Roboto({
  variable: "--font-newform-sans",
  subsets: ["latin"],
});

const geistMono = Epilogue({
  variable: "--font-newform-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className} ${fontSans.className} font-newform! antialiased`}
      >
        <TRPCProvider>
          <AppFlowContextProvider>
            <WillBotTourProvider>{children}</WillBotTourProvider>
          </AppFlowContextProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
